### ISSUE TITLE
PHP8.0 Support

### ISSUE THREAD

**Issue by jrfoell** [awesomemotive/wpforms-phpcs#29]
## Expected Behavior
Able to install `awesomemotive/wpforms-phpcs` with PHP 8.0 (not 8.1 b/c I don't think WPCS upstream supports it yet).

## Current Behavior
- awesomemotive/wpforms-phpcs[v1.0.0, ..., 1.0.6] require php 5.6 - 7.4 -> your php version (8.0.28) does not satisfy that requirement.

Steps to reproduce:
1. Switch to PHP8.0
1. Remove the vendor folder from an upstream dependency (such as `mu-plugins/wpforms-core/vendor`)
1. Run `composer install` from the same upstream dependency location

## Screenshots
![composer2-php8 0](https://user-images.githubusercontent.com/630830/227552814-e2d416f3-3262-42db-9968-2356b464b2a0.png)

**Comment by slaFFik** [comment]
I've just installed v1.1 on PHP 8.2 with no issues.

**Comment by kagg-design** [comment]
I also do not have this problem, so I close the ticket.
