### ISSUE TITLE
Switch to PHPCSStandards/PHP_CodeSniffer

### ISSUE THREAD

**Issue by slaFFik** [awesomemotive/wpforms-phpcs#33]
First, read this issue: https://github.com/squizlabs/PHP_CodeSniffer/issues/3932

Then, modify our `composer.json` to use https://github.com/PHPCSStandards/PHP_CodeSniffer instead of the abandoned https://github.com/squizlabs/PHP_CodeSniffer

**Comment by jrfnl** [comment]
Thank you for your support and your enthousiasm embracing the take-over of the PHP_CodeSniffer package.

In contrast to earlier information, arrangements are now being made to allow the package to continue under its original name on Packagist. The commit (in the new repo) to rename the package [has been reverted](https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/135).

Sorry for the confusion and thank you for understanding. I hope you'll enjoy the 3.8.0 release, which I expect to release this Friday.

**Comment by slaFFik** [comment]
@jrfnl Thank you again so much for the work you do. And even this gesture of yours to contact all the repos who made (or planning to make) the switch to a new repo PHPCSStandards/PHP_CodeSniffer says and means a lot.

As the situation is resolved, we can continue using the same package.
